apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
#  - istio-gw-external.yaml
#  - istio-gw-internal.yaml
#  - istio-argo.yaml

helmCharts:
  - name: gateway
    releaseName: int-gateway
    version: ${ARGOCD_ENV_istio_helm_version}
    repo: https://istio-release.storage.googleapis.com/charts
#    valuesFile: istio-internal-ingress-gateway-values.yaml
#    #namespace: ${ARGOCD_ENV_istio_internal_gateway_namespace}
    namespace: istio-ingress-int
#
  - name: gateway
    releaseName: ext-gateway
    version: ${ARGOCD_ENV_istio_helm_version}
    repo: https://istio-release.storage.googleapis.com/charts
#    valuesFile: istio-external-ingress-gateway-values.yaml
#    #namespace: ${ARGOCD_ENV_istio_external_gateway_namespace}
    namespace: istio-ingress-ext
